Get-AppxPackage *3dbuilder* | Remove-AppxPackage
Get-AppxPackage *officehub* | Remove-AppxPackage
Get-AppxPackage *skypeapp* | Remove-AppxPackage
Get-AppxPackage *getstarted* | Remove-AppxPackage
Get-AppxPackage *zunemusic* | Remove-AppxPackage
Get-AppxPackage *zunevideo* | Remove-AppxPackage
Get-AppxPackage *solitairecollection* | Remove-AppxPackage
Get-AppxPackage *onenote* | Remove-AppxPackage
Get-AppxPackage *windowsphone* | Remove-AppxPackage
Get-AppxPackage *commsphone* | Remove-AppxPackage
Get-AppxPackage *xboxapp* | Remove-AppxPackage
Get-AppxPackage *sway* | Remove-AppxPackage
Get-AppxPackage *messaging* | Remove-AppxPackage
Get-AppxPackage *ConnectivityStore* | Remove-AppxPackage
Get-AppxPackage *Twitter* | Remove-AppxPackage
Get-AppxPackage *Netflix* | Remove-AppxPackage
Get-AppxPackage *WindowsFeedbackHub* | Remove-AppxPackage
Get-AppxPackage *CandyCrushSodaSaga* | Remove-AppxPackage
Get-AppxPackage *FarmVille2CountryEscape* | Remove-AppxPackage
Get-AppxPackage *Asphalt8Airborne* | Remove-AppxPackage
Get-AppxPackage *Flipboard* | Remove-AppxPackage
Get-AppxPackage *AppConnector* | Remove-AppxPackage
Get-AppxPackage *MicrosoftMahjong* | Remove-AppxPackage
Get-AppxPackage *Mahjong* | Remove-AppxPackage
Get-AppxPackage *Sudoku* | Remove-AppxPackage
Get-AppxPackage *NYTCrossword* | Remove-AppxPackage
Get-AppxPackage *Eclipse* | Remove-AppxPackage
Get-AppxPackage *Pandora* | Remove-AppxPackage
Get-AppxPackage *Power* | Remove-AppxPackage
Get-AppxPackage *Network* | Remove-AppxPackage
Get-AppxPackage *Maps* | Remove-AppxPackage
Get-AppxPackage *BingWikipediaBrowser* | Remove-AppxPackage
Get-AppxPackage *Freshpaint* | Remove-AppxPackage
Get-AppxPackage *Wunderlist* | Remove-AppxPackage
Get-AppxPackage *BingTranslator* | Remove-AppxPackage
Get-AppxPackage  microsoft.windowscommunicationsapps | Remove-AppxPackage
Get-AppxPackage *actipro* | Remove-AppxPackage
Get-AppxPackage *BingNews* | Remove-AppxPackage
Get-AppxPackage *People* | Remove-AppxPackage
Get-AppxPackage *BingFinance* | Remove-AppxPackage
Get-AppxPackage *BingWeather* | Remove-AppxPackage
Get-AppxPackage *Wallet* | Remove-AppxPackage
Get-AppxPackage *xbox* | Remove-AppxPackage
Get-AppxPackage *holographic* | Remove-AppxPackage
Get-AppxPackage *3D* | Remove-AppxPackage
Get-AppxPackage *Todo* | Remove-AppxPackage
Get-AppxPackage *whiteboard* | Remove-AppxPackage
Get-AppxPackage *Camera* | Remove-AppxPackage
Get-AppxPackage Microsoft.XboxIdentityProvider | Remove-AppxPackage
Get-AppxPackage Microsoft.XboxGameCallableUI | Remove-AppxPackage
Get-AppxPackage Microsoft.WindowsAlarms | Remove-AppxPackage
Get-AppxPackage StorePurchaseApp | Remove-AppxPackage
Get-AppxPackage *ScreenSketch* | Remove-AppxPackage
Get-AppxPackage *YourPhone* | Remove-AppxPackage
Get-AppxPackage XboxSpeechToTextOverlay | Remove-AppxPackage
Get-AppxPackage XboxGamingOverlay | Remove-AppxPackage
Get-AppxPackage XboxGameOverlay | Remove-AppxPackage
Get-AppxPackage WindowsFeedbackHub | Remove-AppxPackage
Get-AppxPackage *Wallet* | Remove-AppxPackage
Get-AppxPackage *MicrosoftStickyNotes* | Remove-AppxPackage
Get-AppxPackage *Getstarted* | Remove-AppxPackage
Get-AppxPackage *GetHelp* | Remove-AppxPackage
Get-AppxPackage *NetworkSpeedTest* | Remove-AppxPackage
Get-AppxPackage *Advertising* | Remove-AppxPackage
Get-AppxPackage *RemoteDesktop* | Remove-AppxPackage
